server:
  port: 8443
  ssl:
    enabled: true
    key-alias: mylocal-tomcat
    key-password: tomcat
    key-store: classpath:keystore.jks
    key-store-provider: SUN
    key-store-type: JKS
    key-store-password: tomcat
    
# Use Ctrl + Shift + C to comment a line

#spring:
#  jpa:
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl